FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app

# CMD ["sh", "-c", "uvicorn simple:app --host 0.0.0.0 --port 8000"]
# CMD ["uvicorn", "simple:app", "--host", "0.0.0.0", "--port", "8000"]

CMD ["sh", "-c", "cd /app && uvicorn simple:app --host 0.0.0.0 --port 8000 --reload"]