# Utilise une image de base alpine pour sa légèreté 
FROM alpine:latest 

RUN apt-get install python=3.12

# Définir un point d'entrée pour exécuter la commande echo 
ENTRYPOINT ["echo", "Hello, World!"]
